from distutils.core import setup
setup(
    name='jambase_api',
    packages=[
        "jambase_API",
        "jambase_API.APISections",
        "jambase_API.Classes",
        "jambase_API.Enums",
        "jambase_API.ParameterTypes",
    ],
    version='0.1.0',
    description='Python API wrapper for Jambase API',
    author='Evan Swedick',
    license='BSD',
    author_email='eswedick@gmail.com',
    url='https://github.com/eswedick/jambase_api',
    keywords=['cookiecutter', 'template', 'package', ],
    python_requires='>=3.6',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Software Development',
    ],
)
